# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormCreatorTab - SonRise.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 625))
        MainWindow.setMaximumSize(QtCore.QSize(400, 625))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow { background-color: white}")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 383, 581))
        self.widget.setObjectName("widget")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem)
        self.logoLabel = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setAutoFillBackground(False)
        self.logoLabel.setStyleSheet("")
        self.logoLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/Images/list.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setWordWrap(False)
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_7.addWidget(self.logoLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_18.addLayout(self.horizontalLayout_7)
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.saTab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.saTab.setFont(font)
        self.saTab.setStyleSheet("")
        self.saTab.setObjectName("saTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.saTab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.searchLabel = QtWidgets.QLabel(self.saTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLabel.sizePolicy().hasHeightForWidth())
        self.searchLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.searchLabel.setFont(font)
        self.searchLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.searchLabel.setObjectName("searchLabel")
        self.verticalLayout_11.addWidget(self.searchLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLine = QtWidgets.QLineEdit(self.saTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLine.sizePolicy().hasHeightForWidth())
        self.searchLine.setSizePolicy(sizePolicy)
        self.searchLine.setStyleSheet("")
        self.searchLine.setText("")
        self.searchLine.setPlaceholderText("")
        self.searchLine.setObjectName("searchLine")
        self.horizontalLayout.addWidget(self.searchLine)
        self.searchButtonSA = QtWidgets.QPushButton(self.saTab)
        self.searchButtonSA.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.searchButtonSA.setFont(font)
        self.searchButtonSA.setStyleSheet("QPushButton:pressed { \n"
"    border-radius: 4px; \n"
"    background-color: rgb(66, 133, 200);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    font: 75 10pt \"Arial\"; \n"
"    color: rgb(255, 255, 255);    \n"
"    font-weight: bold;\n"
"}")
        self.searchButtonSA.setAutoDefault(False)
        self.searchButtonSA.setDefault(False)
        self.searchButtonSA.setFlat(False)
        self.searchButtonSA.setObjectName("searchButtonSA")
        self.horizontalLayout.addWidget(self.searchButtonSA)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem2)
        self.confirmLabel = QtWidgets.QLabel(self.saTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmLabel.sizePolicy().hasHeightForWidth())
        self.confirmLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmLabel.setFont(font)
        self.confirmLabel.setObjectName("confirmLabel")
        self.verticalLayout_11.addWidget(self.confirmLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.caseNumLabel = QtWidgets.QLabel(self.saTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.caseNumLabel.setFont(font)
        self.caseNumLabel.setObjectName("caseNumLabel")
        self.verticalLayout_6.addWidget(self.caseNumLabel)
        self.nameLabel = QtWidgets.QLabel(self.saTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_6.addWidget(self.nameLabel)
        self.dobLabel = QtWidgets.QLabel(self.saTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dobLabel.setFont(font)
        self.dobLabel.setObjectName("dobLabel")
        self.verticalLayout_6.addWidget(self.dobLabel)
        self.genderLabel = QtWidgets.QLabel(self.saTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.verticalLayout_6.addWidget(self.genderLabel)
        self.nightsLabel = QtWidgets.QLabel(self.saTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nightsLabel.setFont(font)
        self.nightsLabel.setObjectName("nightsLabel")
        self.verticalLayout_6.addWidget(self.nightsLabel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.caseNumLine = QtWidgets.QLineEdit(self.saTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.caseNumLine.setFont(font)
        self.caseNumLine.setStyleSheet("")
        self.caseNumLine.setReadOnly(True)
        self.caseNumLine.setObjectName("caseNumLine")
        self.verticalLayout_7.addWidget(self.caseNumLine)
        self.nameLine = QtWidgets.QLineEdit(self.saTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nameLine.setFont(font)
        self.nameLine.setStyleSheet("")
        self.nameLine.setReadOnly(True)
        self.nameLine.setObjectName("nameLine")
        self.verticalLayout_7.addWidget(self.nameLine)
        self.dobLine = QtWidgets.QLineEdit(self.saTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.dobLine.setFont(font)
        self.dobLine.setStyleSheet("")
        self.dobLine.setReadOnly(True)
        self.dobLine.setObjectName("dobLine")
        self.verticalLayout_7.addWidget(self.dobLine)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.maleRadioBtn = QtWidgets.QRadioButton(self.saTab)
        self.maleRadioBtn.setStyleSheet("selection-color: rgb(85, 170, 255);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.maleRadioBtn.setCheckable(True)
        self.maleRadioBtn.setChecked(False)
        self.maleRadioBtn.setObjectName("maleRadioBtn")
        self.horizontalLayout_19.addWidget(self.maleRadioBtn)
        self.femaleRadioBtn = QtWidgets.QRadioButton(self.saTab)
        self.femaleRadioBtn.setStyleSheet("selection-color: rgb(85, 170, 255);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.femaleRadioBtn.setObjectName("femaleRadioBtn")
        self.horizontalLayout_19.addWidget(self.femaleRadioBtn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_19)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.nightSpinBox = QtWidgets.QSpinBox(self.saTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nightSpinBox.sizePolicy().hasHeightForWidth())
        self.nightSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightSpinBox.setFont(font)
        self.nightSpinBox.setStyleSheet("")
        self.nightSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.nightSpinBox.setMinimum(1)
        self.nightSpinBox.setMaximum(5)
        self.nightSpinBox.setObjectName("nightSpinBox")
        self.verticalLayout_7.addWidget(self.nightSpinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(354, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem3)
        self.createFormBtn = QtWidgets.QPushButton(self.saTab)
        self.createFormBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createFormBtn.sizePolicy().hasHeightForWidth())
        self.createFormBtn.setSizePolicy(sizePolicy)
        self.createFormBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.createFormBtn.setFont(font)
        self.createFormBtn.setStyleSheet("QPushButton:pressed { \n"
"    border-radius: 4px; \n"
"    background-color: rgb(66, 133, 200);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    font: 75 14pt \"Arial\"; \n"
"    color: rgb(255, 255, 255);    \n"
"    font-weight: bold;\n"
"}")
        self.createFormBtn.setObjectName("createFormBtn")
        self.verticalLayout_11.addWidget(self.createFormBtn)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/bed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.saTab, icon1, "")
        self.fvTab = QtWidgets.QWidget()
        self.fvTab.setObjectName("fvTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fvTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.searchLabel_2 = QtWidgets.QLabel(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.searchLabel_2.setFont(font)
        self.searchLabel_2.setObjectName("searchLabel_2")
        self.verticalLayout_5.addWidget(self.searchLabel_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchLine_2 = QtWidgets.QLineEdit(self.fvTab)
        self.searchLine_2.setStyleSheet("")
        self.searchLine_2.setText("")
        self.searchLine_2.setPlaceholderText("")
        self.searchLine_2.setObjectName("searchLine_2")
        self.horizontalLayout_3.addWidget(self.searchLine_2)
        self.searchButtonFV = QtWidgets.QPushButton(self.fvTab)
        self.searchButtonFV.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.searchButtonFV.setFont(font)
        self.searchButtonFV.setStyleSheet("QPushButton:pressed { \n"
"    border-radius: 4px; \n"
"    background-color: rgb(66, 133, 200);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    font: 75 10pt \"Arial\"; \n"
"    color: rgb(255, 255, 255);    \n"
"    font-weight: bold;\n"
"}")
        self.searchButtonFV.setAutoDefault(False)
        self.searchButtonFV.setDefault(False)
        self.searchButtonFV.setFlat(False)
        self.searchButtonFV.setObjectName("searchButtonFV")
        self.horizontalLayout_3.addWidget(self.searchButtonFV)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem4)
        self.confirmLabel_2 = QtWidgets.QLabel(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmLabel_2.setFont(font)
        self.confirmLabel_2.setObjectName("confirmLabel_2")
        self.verticalLayout_5.addWidget(self.confirmLabel_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nameLabel_2 = QtWidgets.QLabel(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_2.setFont(font)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.verticalLayout_3.addWidget(self.nameLabel_2)
        self.dobLabel_2 = QtWidgets.QLabel(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dobLabel_2.setFont(font)
        self.dobLabel_2.setObjectName("dobLabel_2")
        self.verticalLayout_3.addWidget(self.dobLabel_2)
        self.addressLabel = QtWidgets.QLabel(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addressLabel.setFont(font)
        self.addressLabel.setObjectName("addressLabel")
        self.verticalLayout_3.addWidget(self.addressLabel)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.nameLineFV = QtWidgets.QLineEdit(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nameLineFV.setFont(font)
        self.nameLineFV.setStyleSheet("")
        self.nameLineFV.setReadOnly(True)
        self.nameLineFV.setObjectName("nameLineFV")
        self.verticalLayout_4.addWidget(self.nameLineFV)
        self.dobLineFV = QtWidgets.QLineEdit(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.dobLineFV.setFont(font)
        self.dobLineFV.setStyleSheet("")
        self.dobLineFV.setReadOnly(True)
        self.dobLineFV.setObjectName("dobLineFV")
        self.verticalLayout_4.addWidget(self.dobLineFV)
        self.addressLineFV = QtWidgets.QLineEdit(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addressLineFV.sizePolicy().hasHeightForWidth())
        self.addressLineFV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.addressLineFV.setFont(font)
        self.addressLineFV.setStyleSheet("")
        self.addressLineFV.setReadOnly(True)
        self.addressLineFV.setObjectName("addressLineFV")
        self.verticalLayout_4.addWidget(self.addressLineFV)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem5)
        self.confirmLabel_3 = QtWidgets.QLabel(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmLabel_3.setFont(font)
        self.confirmLabel_3.setObjectName("confirmLabel_3")
        self.verticalLayout_5.addWidget(self.confirmLabel_3)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.daysLabel_4 = QtWidgets.QLabel(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.daysLabel_4.setFont(font)
        self.daysLabel_4.setObjectName("daysLabel_4")
        self.horizontalLayout_15.addWidget(self.daysLabel_4)
        self.daysSpinBox = QtWidgets.QSpinBox(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daysSpinBox.sizePolicy().hasHeightForWidth())
        self.daysSpinBox.setSizePolicy(sizePolicy)
        self.daysSpinBox.setStyleSheet("")
        self.daysSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.daysSpinBox.setMinimum(1)
        self.daysSpinBox.setMaximum(4)
        self.daysSpinBox.setObjectName("daysSpinBox")
        self.horizontalLayout_15.addWidget(self.daysSpinBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.daysLabel_5 = QtWidgets.QLabel(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.daysLabel_5.setFont(font)
        self.daysLabel_5.setObjectName("daysLabel_5")
        self.horizontalLayout_16.addWidget(self.daysLabel_5)
        self.adultsSpinBox = QtWidgets.QSpinBox(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adultsSpinBox.sizePolicy().hasHeightForWidth())
        self.adultsSpinBox.setSizePolicy(sizePolicy)
        self.adultsSpinBox.setStyleSheet("")
        self.adultsSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.adultsSpinBox.setMinimum(1)
        self.adultsSpinBox.setMaximum(2)
        self.adultsSpinBox.setObjectName("adultsSpinBox")
        self.horizontalLayout_16.addWidget(self.adultsSpinBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.daysLabel_6 = QtWidgets.QLabel(self.fvTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.daysLabel_6.setFont(font)
        self.daysLabel_6.setObjectName("daysLabel_6")
        self.horizontalLayout_17.addWidget(self.daysLabel_6)
        self.childrenSpinBox = QtWidgets.QSpinBox(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.childrenSpinBox.sizePolicy().hasHeightForWidth())
        self.childrenSpinBox.setSizePolicy(sizePolicy)
        self.childrenSpinBox.setStyleSheet("")
        self.childrenSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.childrenSpinBox.setMaximum(7)
        self.childrenSpinBox.setObjectName("childrenSpinBox")
        self.horizontalLayout_17.addWidget(self.childrenSpinBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.line = QtWidgets.QFrame(self.fvTab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_14.addWidget(self.line)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.foodCheckBox = QtWidgets.QCheckBox(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foodCheckBox.sizePolicy().hasHeightForWidth())
        self.foodCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.foodCheckBox.setFont(font)
        self.foodCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.foodCheckBox.setChecked(False)
        self.foodCheckBox.setObjectName("foodCheckBox")
        self.verticalLayout_12.addWidget(self.foodCheckBox)
        self.diapersCheckBox = QtWidgets.QCheckBox(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diapersCheckBox.sizePolicy().hasHeightForWidth())
        self.diapersCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.diapersCheckBox.setFont(font)
        self.diapersCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.diapersCheckBox.setChecked(False)
        self.diapersCheckBox.setObjectName("diapersCheckBox")
        self.verticalLayout_12.addWidget(self.diapersCheckBox)
        self.fuelCheckBox = QtWidgets.QCheckBox(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuelCheckBox.sizePolicy().hasHeightForWidth())
        self.fuelCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fuelCheckBox.setFont(font)
        self.fuelCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fuelCheckBox.setChecked(False)
        self.fuelCheckBox.setObjectName("fuelCheckBox")
        self.verticalLayout_12.addWidget(self.fuelCheckBox)
        self.horizontalLayout_14.addLayout(self.verticalLayout_12)
        self.line_2 = QtWidgets.QFrame(self.fvTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_14.addWidget(self.line_2)
        self.approvedAmountLabel = QtWidgets.QLabel(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.approvedAmountLabel.sizePolicy().hasHeightForWidth())
        self.approvedAmountLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.approvedAmountLabel.setFont(font)
        self.approvedAmountLabel.setStyleSheet("color: rgb(0, 170, 0)")
        self.approvedAmountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.approvedAmountLabel.setWordWrap(False)
        self.approvedAmountLabel.setObjectName("approvedAmountLabel")
        self.horizontalLayout_14.addWidget(self.approvedAmountLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.safewayLabel = QtWidgets.QLabel(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.safewayLabel.sizePolicy().hasHeightForWidth())
        self.safewayLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.safewayLabel.setFont(font)
        self.safewayLabel.setObjectName("safewayLabel")
        self.horizontalLayout_6.addWidget(self.safewayLabel)
        self.safewayComboBox = QtWidgets.QComboBox(self.fvTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.safewayComboBox.sizePolicy().hasHeightForWidth())
        self.safewayComboBox.setSizePolicy(sizePolicy)
        self.safewayComboBox.setObjectName("safewayComboBox")
        self.horizontalLayout_6.addWidget(self.safewayComboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.createFormBtn_2 = QtWidgets.QPushButton(self.fvTab)
        self.createFormBtn_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.createFormBtn_2.setFont(font)
        self.createFormBtn_2.setStyleSheet("QPushButton:pressed { \n"
"    border-radius: 4px; \n"
"    background-color: rgb(66, 133, 200);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    font: 75 14pt \"Arial\"; \n"
"    color: rgb(255, 255, 255);    \n"
"    font-weight: bold;\n"
"}")
        self.createFormBtn_2.setObjectName("createFormBtn_2")
        self.verticalLayout_5.addWidget(self.createFormBtn_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.fvTab, icon2, "")
        self.sonriseTab = QtWidgets.QWidget()
        self.sonriseTab.setObjectName("sonriseTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sonriseTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchLabel_3 = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.searchLabel_3.setFont(font)
        self.searchLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.searchLabel_3.setObjectName("searchLabel_3")
        self.verticalLayout_2.addWidget(self.searchLabel_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.searchLineSR = QtWidgets.QLineEdit(self.sonriseTab)
        self.searchLineSR.setStyleSheet("")
        self.searchLineSR.setText("")
        self.searchLineSR.setPlaceholderText("")
        self.searchLineSR.setObjectName("searchLineSR")
        self.horizontalLayout_10.addWidget(self.searchLineSR)
        self.searchButtonSR = QtWidgets.QPushButton(self.sonriseTab)
        self.searchButtonSR.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.searchButtonSR.setFont(font)
        self.searchButtonSR.setStyleSheet("QPushButton:pressed { \n"
"    border-radius: 4px; \n"
"    background-color: rgb(66, 133, 200);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    font: 75 10pt \"Arial\"; \n"
"    color: rgb(255, 255, 255);    \n"
"    font-weight: bold;\n"
"}")
        self.searchButtonSR.setAutoDefault(False)
        self.searchButtonSR.setDefault(False)
        self.searchButtonSR.setFlat(False)
        self.searchButtonSR.setObjectName("searchButtonSR")
        self.horizontalLayout_10.addWidget(self.searchButtonSR)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem6 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem6)
        self.confirmLabel_4 = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmLabel_4.setFont(font)
        self.confirmLabel_4.setObjectName("confirmLabel_4")
        self.verticalLayout_2.addWidget(self.confirmLabel_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.caseNumLabel_2 = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.caseNumLabel_2.setFont(font)
        self.caseNumLabel_2.setObjectName("caseNumLabel_2")
        self.verticalLayout_9.addWidget(self.caseNumLabel_2)
        self.nameLabel_3 = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_3.setFont(font)
        self.nameLabel_3.setObjectName("nameLabel_3")
        self.verticalLayout_9.addWidget(self.nameLabel_3)
        self.dobLabel_3 = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dobLabel_3.setFont(font)
        self.dobLabel_3.setObjectName("dobLabel_3")
        self.verticalLayout_9.addWidget(self.dobLabel_3)
        self.genderLabel_2 = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.genderLabel_2.setFont(font)
        self.genderLabel_2.setObjectName("genderLabel_2")
        self.verticalLayout_9.addWidget(self.genderLabel_2)
        self.nightsLabel_2 = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nightsLabel_2.setFont(font)
        self.nightsLabel_2.setObjectName("nightsLabel_2")
        self.verticalLayout_9.addWidget(self.nightsLabel_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.caseNumLineSR = QtWidgets.QLineEdit(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.caseNumLineSR.setFont(font)
        self.caseNumLineSR.setStyleSheet("")
        self.caseNumLineSR.setReadOnly(True)
        self.caseNumLineSR.setObjectName("caseNumLineSR")
        self.verticalLayout_10.addWidget(self.caseNumLineSR)
        self.nameLineSR = QtWidgets.QLineEdit(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nameLineSR.setFont(font)
        self.nameLineSR.setStyleSheet("")
        self.nameLineSR.setReadOnly(True)
        self.nameLineSR.setObjectName("nameLineSR")
        self.verticalLayout_10.addWidget(self.nameLineSR)
        self.dobLineSR = QtWidgets.QLineEdit(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.dobLineSR.setFont(font)
        self.dobLineSR.setStyleSheet("")
        self.dobLineSR.setReadOnly(True)
        self.dobLineSR.setObjectName("dobLineSR")
        self.verticalLayout_10.addWidget(self.dobLineSR)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.maleRadioBtnSR = QtWidgets.QRadioButton(self.sonriseTab)
        self.maleRadioBtnSR.setStyleSheet("selection-color: rgb(85, 170, 255);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.maleRadioBtnSR.setCheckable(True)
        self.maleRadioBtnSR.setChecked(False)
        self.maleRadioBtnSR.setObjectName("maleRadioBtnSR")
        self.horizontalLayout_9.addWidget(self.maleRadioBtnSR)
        self.femaleRadioBtnSR = QtWidgets.QRadioButton(self.sonriseTab)
        self.femaleRadioBtnSR.setStyleSheet("selection-color: rgb(85, 170, 255);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.femaleRadioBtnSR.setObjectName("femaleRadioBtnSR")
        self.horizontalLayout_9.addWidget(self.femaleRadioBtnSR)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.nightSpinBoxSR = QtWidgets.QSpinBox(self.sonriseTab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nightSpinBoxSR.setFont(font)
        self.nightSpinBoxSR.setStyleSheet("")
        self.nightSpinBoxSR.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.nightSpinBoxSR.setMinimum(1)
        self.nightSpinBoxSR.setMaximum(5)
        self.nightSpinBoxSR.setObjectName("nightSpinBoxSR")
        self.verticalLayout_10.addWidget(self.nightSpinBoxSR)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem7)
        self.confirmLabel_5 = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmLabel_5.setFont(font)
        self.confirmLabel_5.setObjectName("confirmLabel_5")
        self.verticalLayout_2.addWidget(self.confirmLabel_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.spouseLabel = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spouseLabel.setFont(font)
        self.spouseLabel.setObjectName("spouseLabel")
        self.verticalLayout_14.addWidget(self.spouseLabel)
        self.numChildLabel = QtWidgets.QLabel(self.sonriseTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.numChildLabel.setFont(font)
        self.numChildLabel.setObjectName("numChildLabel")
        self.verticalLayout_14.addWidget(self.numChildLabel)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.spouseRBYes = QtWidgets.QRadioButton(self.sonriseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spouseRBYes.sizePolicy().hasHeightForWidth())
        self.spouseRBYes.setSizePolicy(sizePolicy)
        self.spouseRBYes.setObjectName("spouseRBYes")
        self.horizontalLayout_12.addWidget(self.spouseRBYes)
        self.spouseRBNo = QtWidgets.QRadioButton(self.sonriseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spouseRBNo.sizePolicy().hasHeightForWidth())
        self.spouseRBNo.setSizePolicy(sizePolicy)
        self.spouseRBNo.setChecked(True)
        self.spouseRBNo.setObjectName("spouseRBNo")
        self.horizontalLayout_12.addWidget(self.spouseRBNo)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.childSRSpinBox = QtWidgets.QSpinBox(self.sonriseTab)
        self.childSRSpinBox.setMaximum(7)
        self.childSRSpinBox.setObjectName("childSRSpinBox")
        self.verticalLayout_15.addWidget(self.childSRSpinBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem8 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem8)
        self.createFormBtn_3 = QtWidgets.QPushButton(self.sonriseTab)
        self.createFormBtn_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.createFormBtn_3.setFont(font)
        self.createFormBtn_3.setStyleSheet("QPushButton:pressed { \n"
"    border-radius: 4px; \n"
"    background-color: rgb(66, 133, 200);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    font: 75 14pt \"Arial\"; \n"
"    color: rgb(255, 255, 255);    \n"
"    font-weight: bold;\n"
"}")
        self.createFormBtn_3.setObjectName("createFormBtn_3")
        self.verticalLayout_2.addWidget(self.createFormBtn_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/family.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.sonriseTab, icon3, "")
        self.verticalLayout_18.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("selection-background-color: rgb(64, 129, 194);\n"
"background-color: rgb(85, 170, 255);    \n"
"color: rgb(255, 255, 255);\n"
"")
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.menuHelp.setFont(font)
        self.menuHelp.setStyleSheet("selection-background-color: rgb(64, 129, 194);\n"
"background-color: rgb(85, 170, 255);    \n"
"color: rgb(255, 255, 255);\n"
"")
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSubmitFeedback = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.actionSubmitFeedback.setFont(font)
        self.actionSubmitFeedback.setObjectName("actionSubmitFeedback")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.menuHelp.addAction(self.actionSubmitFeedback)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form Creator"))
        self.searchLabel.setText(_translate("MainWindow", "Enter a Request Log ID"))
        self.searchButtonSA.setText(_translate("MainWindow", "Search"))
        self.confirmLabel.setText(_translate("MainWindow", "Confirm Client Info"))
        self.caseNumLabel.setText(_translate("MainWindow", "Case Number:"))
        self.nameLabel.setText(_translate("MainWindow", "Client Name:"))
        self.dobLabel.setText(_translate("MainWindow", "Date Of Birth:"))
        self.genderLabel.setText(_translate("MainWindow", "Gender:"))
        self.nightsLabel.setText(_translate("MainWindow", "Nights:"))
        self.maleRadioBtn.setText(_translate("MainWindow", "Male"))
        self.femaleRadioBtn.setText(_translate("MainWindow", "Female"))
        self.createFormBtn.setText(_translate("MainWindow", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saTab), _translate("MainWindow", "Salvation Army"))
        self.searchLabel_2.setText(_translate("MainWindow", "Enter a Request Log ID"))
        self.searchButtonFV.setText(_translate("MainWindow", "Search"))
        self.confirmLabel_2.setText(_translate("MainWindow", "Confirm Client Info"))
        self.nameLabel_2.setText(_translate("MainWindow", "Client Name:"))
        self.dobLabel_2.setText(_translate("MainWindow", "Date Of Birth:"))
        self.addressLabel.setText(_translate("MainWindow", "Address:"))
        self.confirmLabel_3.setText(_translate("MainWindow", "Calculate Approved Amount"))
        self.daysLabel_4.setText(_translate("MainWindow", "Days:"))
        self.daysLabel_5.setText(_translate("MainWindow", "Adults:"))
        self.daysLabel_6.setText(_translate("MainWindow", "Children:"))
        self.foodCheckBox.setText(_translate("MainWindow", "Food"))
        self.diapersCheckBox.setText(_translate("MainWindow", "Diapers"))
        self.fuelCheckBox.setText(_translate("MainWindow", "Fuel"))
        self.approvedAmountLabel.setText(_translate("MainWindow", "$0.00"))
        self.safewayLabel.setText(_translate("MainWindow", "Safeway Location:"))
        self.createFormBtn_2.setText(_translate("MainWindow", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fvTab), _translate("MainWindow", "Food Voucher"))
        self.searchLabel_3.setText(_translate("MainWindow", "Enter a Request Log ID"))
        self.searchButtonSR.setText(_translate("MainWindow", "Search"))
        self.confirmLabel_4.setText(_translate("MainWindow", "Confirm Client Info"))
        self.caseNumLabel_2.setText(_translate("MainWindow", "Case Number:"))
        self.nameLabel_3.setText(_translate("MainWindow", "Client Name:"))
        self.dobLabel_3.setText(_translate("MainWindow", "Date Of Birth:"))
        self.genderLabel_2.setText(_translate("MainWindow", "Gender:"))
        self.nightsLabel_2.setText(_translate("MainWindow", "Nights:"))
        self.maleRadioBtnSR.setText(_translate("MainWindow", "Male"))
        self.femaleRadioBtnSR.setText(_translate("MainWindow", "Female"))
        self.confirmLabel_5.setText(_translate("MainWindow", "Add Dependents"))
        self.spouseLabel.setText(_translate("MainWindow", "Does the client have a spouse: "))
        self.numChildLabel.setText(_translate("MainWindow", "Number of children: "))
        self.spouseRBYes.setText(_translate("MainWindow", "Yes"))
        self.spouseRBNo.setText(_translate("MainWindow", "No"))
        self.createFormBtn_3.setText(_translate("MainWindow", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sonriseTab), _translate("MainWindow", "Son Rise Village"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSubmitFeedback.setText(_translate("MainWindow", "Submit Feedback"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
import resource
